#!/bin/sh

walloptions="--zoom"

while read file; do
  case "$1" in
    "C-w")
      # xwallpaper --zoom "$file"
      xwallpaper $walloptions "$file"
      echo -e "#!/bin/sh\nxwallpaper $walloptions \"$(readlink -e "$file")\"" > $HOME/.config/wallpaper
      chmod 755 $HOME/.config/wallpaper
      ;;
  esac
done
